### ISSUE TITLE
Crash while applying filters on 3C295

### ISSUE THREAD

**Issue by boutigny** [nicolaschotard/Clusters#20]
I get the following crash

INFO: Applying filters on the data to keep a clean sample of galaxies
INFO: Loading data from /home/boutigny/LSST/CFHT/clusters/3C295/output/coadd_dir
CameraMapper INFO: Unable to locate calibRegistry registry in root: /home/boutigny/LSST/CFHT/clusters/3C295/output/coadd_dir/calibRegistry.sqlite3
CameraMapper INFO: Unable to locate calibRegistry registry in current dir: ./calibRegistry.sqlite3
CameraMapper INFO: Loading Posix registry from /home/boutigny/LSST/CFHT/clusters/3C295/output/coadd_dir
Traceback (most recent call last):
  File "/home/boutigny/LSST/new/lsstsw/miniconda/bin/clusters_data.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/boutigny/LSST/DESC/Clusters/Clusters/scripts/clusters_data.py", line 7, in <module>
    sys.exit(data.load_data())
  File "/home/boutigny/LSST/DESC/Clusters/Clusters/clusters/mains/data.py", line 58, in load_data
    data.catalogs = cdata.filter_table(catalogs)
  File "/home/boutigny/LSST/DESC/Clusters/Clusters/clusters/data.py", line 534, in filter_table
    dmg = cats['deepCoadd_meas'][filt].group_by('id')
  File "/home/boutigny/LSST/new/lsstsw/miniconda/lib/python2.7/site-packages/astropy/table/table.py", line 2394, in group_by
    return groups.table_group_by(self, keys)
  File "/home/boutigny/LSST/new/lsstsw/miniconda/lib/python2.7/site-packages/astropy/table/groups.py", line 21, in table_group_by
    return _table_group_by(table, keys)
  File "/home/boutigny/LSST/new/lsstsw/miniconda/lib/python2.7/site-packages/astropy/table/groups.py", line 95, in _table_group_by
    out_keys = table_keys[indices[:-1]]
  File "/home/boutigny/LSST/new/lsstsw/miniconda/lib/python2.7/site-packages/astropy/table/table.py", line 1112, in __getitem__
    return self._new_from_slice(item)
  File "/home/boutigny/LSST/new/lsstsw/miniconda/lib/python2.7/site-packages/astropy/table/table.py", line 711, in _new_from_slice
    newcol = col[slice_]
  File "astropy/table/_column_mixins.pyx", line 70, in astropy.table._column_mixins._ColumnGetitemShim.__getitem__ (astropy/table/_column_mixins.c:900)
  File "astropy/table/_column_mixins.pyx", line 61, in astropy.table._column_mixins.base_getitem (astropy/table/_column_mixins.c:786)
  File "astropy/table/_column_mixins.pyx", line 65, in astropy.table._column_mixins.column_getitem (astropy/table/_column_mixins.c:837)
IndexError: index 0 is out of bounds for axis 1 with size 0

**Comment by nicolaschotard** [comment]
Can you localy try to change the followig line of clusters/data.py by replacing 'id' by 'objectId'? They might have corrected a bug in the stack for the deepCoadd_meas catalog, which was using the ID key 'id' instead of 'objectId'.

Before correction:

```
File "/home/boutigny/LSST/DESC/Clusters/Clusters/clusters/data.py", line 534, in filter_table
dmg = cats['deepCoadd_meas'][filt].group_by('id')
```

After correction

`dmg = cats['deepCoadd_meas'][filt].group_by('objectId')`

Please let e know if that does not work.

**Comment by nicolaschotard** [comment]
There is actually a grouping using the 'id' key line 509, right before it crashes

`nfilt = len(cats['deepCoadd_meas'].group_by('id').groups[0])`

So this cannot be a key problem. It must be that the filters applied before the grouping filtered out all sources, and you probably end up with an empty table, which explains the `IndexError`. We should check if the table is indeed empty, and understand why.

**Comment by nicolaschotard** [comment]
The reason why everything is filtered out is because all values for the cats['deepCoadd_meas']['base_ClassificationExtendedness_value'] are set to NaN, and all the flags to 1. We have to investigate that.

**Comment by boutigny** [comment]
I checked directly in the deepCoadd_meas from the stack output and all the base_ClassificationExtendedness_flags are set to 1. So something is screwed up at the stack level :-

**Comment by boutigny** [comment]
The problem  is understood (thanks Jim Bosch). This is because I haven't run CModel in processCcd. The bad news is that the 3C295 processing is useless and I have to redo it from scratch.
