### ISSUE TITLE
Crash of clusters_mass.py due to an AssertionError

### ISSUE THREAD

**Issue by nicolaschotard** [nicolaschotard/Clusters#8]
I've tested clusters_mass.py on a (as clean as possible) sample of galaxies, and this always ends up with the following assertionError after a few hundreds iterations (from 200 to 4000 depending on the run):

```
At Iteration 1600
Traceback (most recent call last):
  File "/home/chotard/Work/lsstsw/miniconda/bin/clusters_mass.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/chotard/Work/scripts/analysis/Packages/Clusters/scripts/clusters_mass.py", line 7, in <module>
    sys.exit(main.mass())
  File "/home/chotard/Work/scripts/analysis/Packages/Clusters/clusters/main.py", line 481, in mass
    masscontroller.run()
  File "/home/chotard/Work/scripts/analysis/Packages/Clusters/pzmassfitter/maxlike_controller.py", line 152, in run
    self.runmethod.run(self)
  File "/home/chotard/Work/scripts/analysis/Packages/Clusters/pzmassfitter/maxlike_masses.py", line 441, in run
    runner.run(mcmc_manager)
  File "/home/chotard/Work/scripts/analysis/Packages/Clusters/pzmassfitter/pymc_mymcmc_adapter.py", line 313, in run
    manager.engine(options.nsamples, None, backends)
  File "/home/chotard/Work/scripts/analysis/Packages/Clusters/pzmassfitter/mymc.py", line 1245, in __call__
    updater(struct)
  File "/home/chotard/Work/scripts/analysis/Packages/Clusters/pzmassfitter/mymc.py", line 578, in __call__
    self.do_adapt(struct)
  File "/home/chotard/Work/scripts/analysis/Packages/Clusters/pzmassfitter/mymc.py", line 594, in do_adapt
    if self.set_covariance(cov) and not self.onAdapt is None:
  File "/home/chotard/Work/scripts/analysis/Packages/Clusters/pzmassfitter/mymc.py", line 704, in set_covariance
    assert((np.array(self.widths) != 0.).all())
AssertionError
```

Is there a way to fix that of is it at least possible to catch it and exit peacefully as if a ctr-c was used?

**Comment by nicolaschotard** [comment]
I believe this has been resolved and merged. Douglas, should we close this issue?

**Comment by deapplegate** [comment]
Yes, issue resolved.
